################################################################################
#               Settings for high-frequency intraday scalping bot             #
#          Pairs: BTC, ETH, SOL, DOGE, SUI, XRP, ADA  •  HFT edition          #
################################################################################

############################  Connection / Exchange   #############################
[bybit]
api_key    = "zf72Bea3s8kMDd031d"
api_secret = "XMfDkNDUNRXWbSAkkSY5Prvz59lWaWIIzgw5"
testnet    = false
demo       = true
channel_type = "linear"
symbols = [ "BTCUSDT","ETHUSDT","SOLUSDT","DOGEUSDT","SUIUSDT","XRPUSDT","ADAUSDT" ]

#############################     Telegram alerts      #############################
[telegram]
bot_token = "7994411518:AAHpNIzjjN3TOl4TvYbEF7B2_Bxod3IxDTE"
chat_id   = "-1002593601621"
##############################   Core trade engine   ############################
[trading]
leverage                 = 50
initial_risk_percent     = 0.25
dca_risk_multiplier      = 1.40
soft_sl_percent          = -1.5
take_profit_percent      = 0.40
tp1_percent              = 0.35
tp1_close_ratio          = 0.45
tp2_percent              = 0.70
tp2_close_ratio          = 0.30
trailing_distance_percent= 0.20
min_profit_to_be         = 0.10
enable_risk_cap          = true
max_position_risk_percent= 20.0        # ≤ 20 % equity

##############################   Global risk guard   ############################
[risk]
daily_drawdown_percent      = -5.0
enable_daily_drawdown_guard = true
daily_profit_percent        = 0.0
enable_daily_profit_guard   = false
max_open_positions          = 8

############################   Entry-score baseline  ############################
[entry_score]
weights           = { z=1.0, obi=0.8, vbd=0.6, spread=0.4, tflow=0.6, volatility=1.5 }
long_threshold    = -1.5
short_threshold   =  1.5
threshold_k       =  1.8
symbol_weights    = {}
symbol_threshold_k= {}

############################   Per-symbol overrides  ############################
[symbol_params.BTCUSDT]
dca_max     = 3
hedge_ratio = 0.50

[symbol_params.ETHUSDT]
dca_max     = 3
hedge_ratio = 0.50

[symbol_params.1000PEPEUSDT]
bb_dev      = 2.5
dca_max     = 1
hedge_ratio = 0.30

# All other pairs inherit defaults:
# atr_period = 14, bb_dev = 2.0, dca_max = 2, hedge_ratio = 0.50
################################################################################
