################################################################################
#                         HFT-bounce — settings.toml                           #
################################################################################

###########################  Exchange connection  ##############################
[bybit]
api_key       = "zf72Bea3s8kMDd031d"          # ← замените при необходимости
api_secret    = "XMfDkNDUNRXWbSAkkSY5Prvz59lWaWIIzgw5"
testnet       = false
demo          = true
place_orders  = true
channel_type  = "linear"
symbols       = [
  "BTCUSDT","ETHUSDT","SOLUSDT","DOGEUSDT",
  "SUIUSDT","XRPUSDT","ADAUSDT","1000PEPEUSDT"
]

###############################  Core trading  #################################
[trading]
leverage                  = 50            # плечо Bybit
initial_risk_percent      = 0.5          # риск первой сделки (% от equity)

# — глобальный риск-кэп —
enable_risk_cap           = true
max_position_risk_percent = 20.0          # суммарный открытый риск ≤20 % equity

# — DCA (SmartDCA всё равно применит свои капы) —
max_dca_levels            = 4
dca_risk_multiplier       = 1.30

# — SL / TP / Trailing —
soft_sl_percent           = -50.0
take_profit_percent       = 1.0
tp1_percent               = 0.35
tp1_close_ratio           = 0.45
tp2_percent               = 0.70
tp2_close_ratio           = 0.30
trailing_distance_percent = 0.20
break_even_after_minutes  = 0
min_profit_to_be          = 0.30

# Hybrid strategy options
strategy_mode            = "hybrid"
enable_mm               = true
mm_spread_percent       = 0.2
mm_refresh_seconds      = 10
enable_mom_filter       = false
momentum_period         = 5
use_ml_scoring          = false
use_atr_stop            = true
atr_stop_multiplier     = 1.5
hard_sl_percent         = 2.0
enable_stat_arb         = true
stat_arb_entry_z        = 1.0
stat_arb_exit_z         = 0.5
stat_arb_stop_z         = 4.0

# — опциональные фильтры (старый код) —
enable_rsi_filter         = true
rsi_period                = 14
rsi_overbought            = 70.0
rsi_oversold              = 30.0

use_adx_filter            = true
adx_period                = 14
adx_threshold             = 25.0

# — хедж —
enable_hedging            = true
max_hedges                = 5
hedge_delay_seconds       = 2
candle_interval_sec       = 1     # длина свечи (с) для быстрой инициализации

########################  Multi-time-frame filter  #############################
[multi_tf]
enable              = false
intervals           = ["1m","3m","5m"]
weights             = { "1m" = 0.5, "3m" = 0.3, "5m" = 0.2 }
update_seconds      = 15
trend_confirm_bars  = 2

#############################  Global risk  ####################################
[risk]
daily_drawdown_percent       = -99.0
enable_daily_drawdown_guard  = true
daily_profit_percent         =  0.0
enable_daily_profit_guard    = false
max_open_positions           = 8            # фиксировано по ТЗ
daily_trades_limit          = 1000
enable_daily_trades_guard   = true

###########################  Telegram notifier  ################################
[telegram]
bot_token = "7994411518:AAHpNIzjjN3TOl4TvYbEF7B2_Bxod3IxDTE"
chat_id   = "-1002593601621"

#########################  Entry-score parameters  #############################
[entry_score]
weights            = { z=1.0, obi=0.8, vbd=0.6, spread=0.4, tflow=0.6, volatility=1.5 }
long_threshold     = -1.5
short_threshold    =  1.5
threshold_k        =  1.8
symbol_weights     = {}
symbol_threshold_k = {}

######################  Per-symbol overrides (symbol_params)  ##################
# Дефолты из SymbolParams (если секция не указана):
#   atr_period = 14, bb_dev = 2.0, dca_max = 2, hedge_ratio = 0.50

[symbol_params.BTCUSDT]
dca_max     = 3
hedge_ratio = 0.50     

[symbol_params.ETHUSDT]
dca_max     = 3
hedge_ratio = 0.50     

[symbol_params.1000PEPEUSDT]
bb_dev      = 2.5      # расширенный BB
dca_max     = 1
hedge_ratio = 0.30    

# Остальные пары (SOL, DOGE, SUI, XRP, ADA) унаследуют дефолты.
################################################################################
