[bybit]
api_key       = "zf72Bea3s8kMDd031d"          
api_secret    = "XMfDkNDUNRXWbSAkkSY5Prvz59lWaWIIzgw5"
symbols      = ["BTCUSDT"]
testnet      = false
demo         = false
place_orders = false
channel_type = "linear"

[trading]
strategy_mode = "mean_reversion"
mr_bb_dev     = 2.0
mr_rsi_low    = 30
mr_rsi_high   = 70

[risk]
daily_drawdown_percent = -5.0
max_open_positions     = 5
daily_trades_limit     = 20

[telegram]
bot_token = "7994411518:AAHpNIzjjN3TOl4TvYbEF7B2_Bxod3IxDTE"
chat_id   = "-1002593601621"
