name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install pytest ruff
      - name: Lint
        run: ruff check --fix app legacy tests scripts
      - name: Run tests
        run: pytest -q --cov
